[package]
name = "boot"
version = "0.1.0"

[lib]
name = "boot"
path = "src/main.rs"
crate-type = ["staticlib"]

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
features = []

[dependencies]
orbclient = { path = "orbclient" }
uefi = { git = "https://github.com/redox-os/uefi.git" }
uefi_alloc = { git = "https://github.com/redox-os/uefi_alloc.git" }
wstr = "0.1"
x86 = "0.7"
