[package]
name = "redox_bootloader"
version = "0.1.0"

[lib]
name = "redox_bootloader"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
features = ["mem"]

[dependencies.goblin]
version = "0.0.14"
default-features = false
features = ["elf64"]

[dependencies]
dmi = { path = "dmi" }
orbclient = { path = "orbclient" }
plain = "0.1"
uefi = { path = "uefi" }
uefi_alloc = { path = "uefi_alloc" }
x86 = "0.7"
