[package]
name = "firmware_update"
version = "0.1.0"

[lib]
name = "system76-fu"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins"
features = ["mem"]

[dependencies]
dmi = { path = "dmi" }
ecflash = { git = "https://github.com/system76/ecflash.git" }
orbclient = { path = "orbclient" }
plain = "0.1"
uefi = { path = "uefi" }
uefi_alloc = { path = "uefi_alloc" }
x86 = "0.7"
